# Generated by Django 4.2.2 on 2023-07-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_product_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
