# Generated by Django 4.2.2 on 2023-07-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
