# Generated by Django 4.2.2 on 2023-07-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'жалобы'},
        ),
    ]
